apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
  labels:
    app: calc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc-container
        image: gtkachenko1990/test-calc:main-123
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

