---
- hosts: all

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    k8s_kubeconfig: ~/.kube/config-k8s-cluster
    k8s_manifests_base_dir: ../Kubernetes
    k8s_manifests:
      - deployment

    roles:
      - role: geerlingguy.k8s_manifests
